"""main.py"""
STARTINGWIDTH: int = 800
STARTINGHEIGHT: int = 600

INPUTWINDOWWIDTH: int = 300
ZOOMINTENSITY: int = 5

"""input.py"""
BOXHEIGHT: int = 100
HEADERHEIGHT: int = 80

"""inputBox.py"""
BACKSPACESTARTTIMER: float = 0.5
BACKSPACEBETWEENTIMER: float = 0.05
