"""main.py"""
STARTINGWIDTH: int = 800
STARTINGHEIGHT: int = 600

INPUTWINDOWWIDTH: int = 300
ZOOMINTENSITY: int = 5

"""grid.py"""
MAXSCALE: int = 10 ** 7

MINIMUMDISPLAYSCALE: int = 85
MAXIMUMDISPLAYSCALE: int = 170

UNFOCUSEDLINEWIDTH: int = 2
FOCUSEDLINEWIDTH: int = 3

"""input.py"""
BOXHEIGHT: int = 100
HEADERHEIGHT: int = 80

PLUSVERTICALRECTWIDTH: int = 6
PLUSVERTICALRECTHEIGHT: int = 26
PLUSBORDERWIDTH: int = 2

"""inputBox.py"""
BACKSPACESTARTTIMER: float = 0.5
BACKSPACEBETWEENTIMER: float = 0.05
